from pathlib import Path


def remediation_for(finding):
    if finding.category == "missing":
        return (
            "Define this configuration key in the missing environment, "
            "or explicitly document why it is optional there."
        )

    if finding.category == "type-mismatch":
        return (
            "Normalize the configuration type across all environments "
            "(for example, use numeric values everywhere or string values everywhere)."
        )

    if finding.category == "orphaned":
        return (
            "Remove the unused configuration key, or document/allowlist it "
            "if it is intentionally reserved for infrastructure or another deployment path."
        )

    return "Review this configuration difference."


def render_markdown(
    path: Path,
    findings,
    new_fps,
    previous_fps,
    resolved_fps,
    repo_name,
):
    new = [f for f in findings if f.fingerprint in new_fps]
    still = [f for f in findings if f.fingerprint in previous_fps]

    lines = [
        "# Config Drift Report",
        "",
        f"**Repository:** `{repo_name}`",
        "",
        "> **Security guarantee:** No raw configuration value is written "
        "to this report, console, logs, or state.",
        "",
        "## Summary",
        "",
        f"- Findings: **{len(findings)}**",
        f"- New since last run: **{len(new)}**",
        f"- Still unresolved: **{len(still)}**",
        f"- Resolved since last run: **{len(resolved_fps)}**",
        "",
    ]

    sections = [
        (
            "Critical: Missing in an environment",
            [f for f in findings if f.category == "missing"],
        ),
        (
            "Warning: Inconsistent across environments",
            [f for f in findings if f.category == "type-mismatch"],
        ),
        (
            "Info: Orphaned config",
            [f for f in findings if f.category == "orphaned"],
        ),
    ]

    for title, group in sections:
        lines += [f"## {title}", ""]

        if not group:
            lines += ["_None._", ""]
            continue

        for finding in group:
            status = (
                "NEW"
                if finding.fingerprint in new_fps
                else "STILL UNRESOLVED"
                if finding.fingerprint in previous_fps
                else "CURRENT"
            )

            lines += [
                f"### `{finding.key}`",
                f"- **Status:** `{status}`",
                f"- **Severity:** `{finding.severity}`",
                f"- **Used at:** `{finding.used_at or 'No code reference'}`",
                f"- **Defined in:** "
                f"{', '.join(finding.defined_in) or 'none'}",
                f"- **Missing in:** "
                f"{', '.join(finding.missing_in) or 'none'}",
                f"- **Config source:** "
                f"{', '.join(finding.sources) or 'none'}",
                f"- **Note:** {finding.note}",
                f"- **Recommended action:** {remediation_for(finding)}",
                "",
            ]

    if resolved_fps:
        lines += [
            "## Resolved",
            "",
            f"{len(resolved_fps)} finding(s) disappeared since the previous run.",
            "",
        ]

    lines += [
        "---",
        "",
        "_Generated by Drift Watch. Secret values are intentionally "
        "unavailable to the reporter._",
        "",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")